name: macOS

on: [push]

jobs:
  macOS:
    name: macOS
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew
        run: brew update

      - name: Install Neovim
        run: brew install neovim

      - name: Setup
        run: bash ./install.sh
