name: Pages

on: [push]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  pages:
    name: Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p out
      - run: cp -f install.sh out/
      - run: touch out/.nojekyll

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
        if: github.ref == 'refs/heads/main'
